# -*- coding: utf-8 -*-
"""salary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bryK_x2aYB8w16jf8kMdPROj80KG976H
"""

# salary calculator
print('Please enter your salary:')
inputString = input()
inputValue =int(inputString)

if inputValue <= 11000:
  netValue = inputValue
elif inputValue <= 25000:
  incomeTax = (inputValue - 11000) * 0.365
  netValue = inputValue - incomeTax
elif inputValue <= 60000:
  incomeTax = (inputValue - 25000) * 0.4321 + 5110
  netValue = inputValue - incomeTax
else:
  incomeTax = (inputValue - 60000) * 0.5 + 20235
  netValue = inputValue - incomeTax

print('Your netValue is ' + str(netValue))